[package]
name = "rust-binary-search"
version = "0.1.0"
authors = ["Thomas Chaplin <thomaschaplin@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
